### ISSUE TITLE
App crashes if using the German game files

### ISSUE THREAD

**Issue by xxmichibxx** [MrHuu/fallout1-ce-3ds#3]
Hi, I was trying to use your app with the German language game files (Version 1.1) from Steam, but the 3DS crashes instantly. I've attached the Luma3DS log for more details. Thanks for any help!
[crash_dump_00000000.dmp](https://github.com/MrHuu/fallout1-ce-3ds/files/15338481/crash_dump_00000000.dmp)

**Comment by MrHuu** [comment]
Next to ```critter.dat```, ```master.dat``` and the ```data``` folder, also copy ```fallout.cfg``` from the german steam version to your sd card.

**Comment by xxmichibxx** [comment]
Copying the `fallout.cfg` from the game files fixed my issue. Thanks! Sadly this wasn't metioned in the GBAtemp thread.
