### ISSUE TITLE
Is there a setup requirement?

### ISSUE THREAD

**Issue by KatoOhashi** [MrHuu/fallout1-ce-3ds#4]
Is there a setup requirement? just incase its needed i own all titles for fallout through steam and epic as well.

I'm curious becuase i did try to launch this on its own and the 3ds crashed on first run this was running on my OG 3ds not the New 3DS or any of that.

Edit 1
I apologize if this was said somehwere but all i found in your readme section was a copy and paste of Fallout CE's Readme  im unsure if theres actually any clarification as i got tired of scanning the readme section.

Edit 1.5
 I found your forum post on gba temp nevermind i got it running i wont tell you what to do but i advise making sure people know what to do with your amazing creation generally speaking i was just googling dos box stuff and found your git hub so i started exploring it since i was going to try to run the older Variant of Fallout 1 the dosbox version on your dosbox for 3ds application but found this treasure instead so now i got both applications on my 3ds and im all set! 

5/5 star work your doing my good friend! if there was a review page for creations on git hub id probably be preaching about how amazing this implementation of fallout 1 is !

edit 2
 PS. i will leave this ticket open so you can see the issue i had still without needing to go on a wild goose chase or any of that stuff! close it at your descretion Mr.Huu :D

**Comment by Mystic-Maybe** [comment]
I am having the same problem here and I can only see JatoOhashi's side of the conversation and because of that I don't really know how to fix the problem. I used the .cia file through the FBI app on my original 3ds and I can see the icon pop up properly but when I open it it gives an error and crashes. I have the critter.dat master.dat and data folder all together in a folder with the .cia in its own fallout folder. Any advice would be greatly appreciated.

**Comment by cosmoanton** [comment]
> I am having the same problem here and I can only see JatoOhashi's side of the conversation and because of that I don't really know how to fix the problem. I used the .cia file through the FBI app on my original 3ds and I can see the icon pop up properly but when I open it it gives an error and crashes. I have the critter.dat master.dat and data folder all together in a folder with the .cia in its own fallout folder. Any advice would be greatly appreciated.

You have to download fallout-ce from this [link](https://github.com/alexbatalov/fallout1-ce/releases) and put it in 3ds/fallout

**Comment by prodnazgul** [comment]
> > I am having the same problem here and I can only see JatoOhashi's side of the conversation and because of that I don't really know how to fix the problem. I used the .cia file through the FBI app on my original 3ds and I can see the icon pop up properly but when I open it it gives an error and crashes. I have the critter.dat master.dat and data folder all together in a folder with the .cia in its own fallout folder. Any advice would be greatly appreciated.
> 
> You have to download fallout-ce from this [link](https://github.com/alexbatalov/fallout1-ce/releases) and put it in 3ds/fallout

which ce? all of them say for windows or other devices. i have the same problem he does.

**Comment by cosmoanton** [comment]
> > > I am having the same problem here and I can only see JatoOhashi's side of the conversation and because of that I don't really know how to fix the problem. I used the .cia file through the FBI app on my original 3ds and I can see the icon pop up properly but when I open it it gives an error and crashes. I have the critter.dat master.dat and data folder all together in a folder with the .cia in its own fallout folder. Any advice would be greatly appreciated.
> > 
> > 
> > You have to download fallout-ce from this [link](https://github.com/alexbatalov/fallout1-ce/releases) and put it in 3ds/fallout
> 
> which ce? all of them say for windows or other devices. i have the same problem he does.

I downloaded the x64 windows version, and it worked perfectly for me

**Comment by prodnazgul** [comment]
> it

okay cool thank you! what exactly does yours look like though? what all is there? in mine i have the ".dat files" my "data folder" from steam (would that matter?) a ".cfg file" (is that needed, if so did i make it right) and then i used the fallout cia install. i feel like im very close to getting this to work and i know it seems simple but i guess im missing something. maybe its my data folder from steam? i made the cfg file for it too so maybe that wasn't right? not sure kinda stuck and can't find much info on this. was told asking around works

**Comment by cosmoanton** [comment]
In min

> > it
> 
> okay cool thank you! what exactly does yours look like though? what all is there? in mine i have the ".dat files" my "data folder" from steam (would that matter?) a ".cfg file" (is that needed, if so did i make it right) and then i used the fallout cia install. i feel like im very close to getting this to work and i know it seems simple but i guess im missing something. maybe its my data folder from steam? i made the cfg file for it too so maybe that wasn't right? not sure kinda stuck and can't find much info on this. was told asking around works

In the directory you should have 4 things: the DATA folder from steam, the fallout-ce.exe file, and both the CRITTER.DAT and MASTER.DAT file

**Comment by MrHuu** [comment]
> In min
> 
> > > it
> > 
> > 
> > okay cool thank you! what exactly does yours look like though? what all is there? in mine i have the ".dat files" my "data folder" from steam (would that matter?) a ".cfg file" (is that needed, if so did i make it right) and then i used the fallout cia install. i feel like im very close to getting this to work and i know it seems simple but i guess im missing something. maybe its my data folder from steam? i made the cfg file for it too so maybe that wasn't right? not sure kinda stuck and can't find much info on this. was told asking around works
> 
> In the directory you should have 4 things: the DATA folder from steam, the fallout-ce.exe file, and both the CRITTER.DAT and MASTER.DAT file

This is false. The .exe is the executable for windows. It is replaced by either .3dsx or .cia.
The main readme is NOT updated to add 3DS instructions yet.

You only need ```CRITTER.DAT``` and ```MASTER.DAT```.
The ```DATA``` folder contains additional patches and music, so this is recommended.
