### ISSUE TITLE
Running into a Crash right after exiting vault 13

### ISSUE THREAD

**Issue by Fr3ShTech** [MrHuu/fallout1-ce-3ds#5]
[crash_dump_00000000.dmp](https://github.com/MrHuu/fallout1-ce-3ds/files/15505597/crash_dump_00000000.dmp)

After starting the game, its crashing every time when i take dmg from a rat in the cave. I can kill them no problem, if they hit me i get: 
Processor : ARM11 (core 0)
Exception type : data abort
fault status : Translation - section

I saved the crash dump, so you can maybe work this bug out. Im using an o3ds and Luma v 13.0.2. I never encountered a crash in any other game. It could of course also be a problem with my fallout data.
Thanks in advance

**Comment by TheMasterCoders** [comment]
git gud

**Comment by MrHuu** [comment]
If you still running into issues, please report here: [https://github.com/MrHuu/fallout1-ce-3ds/issues/6](https://github.com/MrHuu/fallout1-ce-3ds/issues/6)
