### ISSUE TITLE
Dethrace

### ISSUE THREAD

**Issue by regionalradio** [MrHuu/fallout1-ce-3ds#8]
The 3ds dethrace page won't allow issues to be made, but is it still planned to be worked on?

**Comment by MrHuu** [comment]
Short answer, no.

Long answer... err also no currently. I do want to add audio eventually. It would be nice if we get some pthread support with libctru, which should be on it's way. But looking at the current low performance, with added audio it's going to be even slower.
So the only way forward would be a hardware renderer. While i would like to create it, the existing code uses shaders a lot. And i'm currently not interested in learning on how to adapt these shaders to a functional renderer for 3ds. Maybe in the future, when i've finally finished some other projects, or if the dethrace codebase allows easy adapting the gl renderers with less shaders.
